app = "mbgc-importer-service"
primary_region = "iad"

[build]
  dockerfile = "deploy/Dockerfile"

[http_service]
  internal_port = 8003
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "10s"
    timeout  = "5s"
    grace_period = "5s"
    method = "GET"
    path   = "/healthz"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PORT           = "8003"
  SYNC_LIMIT_USER  = "3"
  SYNC_LIMIT_ADMIN = "20"
